version: '3.1'
services:
   mysql:
     image: mysql:5.7
     ports:
       - '3306:3306'
     secrets:
       - DB_ROOT_PASSWORD
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/DB_ROOT_PASSWORD
       MYSQL_DATABASE: example
     deploy:
       replicas: 1
       placement:
         constraints: [node.role == worker]
secrets:
  DB_ROOT_PASSWORD:
    external: true
volumes:
    db_data:
