version: '3.1'

services:
   mysql:
     image: mysql:5.7
     ports:
       - '3306:3306'
     secrets:
       - DB_ROOT_PASSWORD
       - DB_PASSWORD
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/DB_ROOT_PASSWORD
       MYSQL_DATABASE: example
       MYSQL_USER: user
       MYSQL_PASSWORD_FILE: /run/secrets/DB_PASSWORD

secrets:
  DB_ROOT_PASSWORD:
    external: true
  DB_PASSWORD:
    external: true

volumes:
    db_data:
