version: "3"
services:
  nodejs:
    image: docker.io/kalise/nodejs-web-app:latest
    ports:
      - "80:8080"
    environment:
      MESSAGE: 'Hello Docker Swarm'
    networks:
      - application_network
    volumes:
      - log-volume:/var/log
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: pause
        max_failure_ratio: 0
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
volumes:
  log-volume:
    driver: local
networks:
  application_network:
    driver: overlay
    ipam:
     driver: default
     config:
       - subnet: 172.128.1.0/24
