version: "3.1"
services:

  vote:
    image: docker.io/kalise/vote-app:latest
    environment:
      DB_TYPE: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: votedb
      DB_USER: user
      DB_PASS: /run/secrets/db_password
    ports:
      - "8000:5000"
    networks:
      - application_network
    volumes:
      - log-volume:/app/log:rw
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: pause
        max_failure_ratio: 0
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]

  mysql:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
      #MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: votedb
      MYSQL_USER: user
      MYSQL_PASSWORD: /run/secrets/db_password
    volumes:
      - data:/var/lib/mysql:rw
    networks:
      - application_network
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]

secrets:
   db_password:
     file: db_password.txt
   db_root_password:
     file: db_root_password.txt

volumes:
  log-volume:
    driver: local

  data:
    driver: local

networks:
  application_network:
    driver: overlay
    ipam:
     driver: default
     config:
       - subnet: 172.128.1.0/24
