# First create password files
# echo Th1s1sA5tr0nGpa55w0rD! > db_password.txt
# echo Th1s1sA5tr0nG%ooTpa55w0rD! > db_root_password.txt
# then deploy the application stacks
# docker stack deploy -c wp-stack-secrets.yaml myapp
# and finally remove the files from the system
# rm -rf db_password.txt db_root_password.txt
#
version: '3.1'
services:
  mariadb:
    image: bitnami/mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: /run/secrets/db_root_password
      MARIADB_DATABASE: wordpress
      MARIADB_USER: bitnami
      MARIADB_PASSWORD: /run/secrets/db_password
    volumes:
      - mariadb-data:/bitnami/mariadb
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
  wordpress:
    image: bitnami/wordpress:latest
    environment:
      MARIADB_HOST: mariadb
      MARIADB_PORT: 3306
      WORDPRESS_DATABASE_NAME: wordpress
      WORDPRESS_DATABASE_USER: bitnami
      WORDPRESS_DATABASE_PASSWORD: /run/secrets/db_password
    ports:
      - '80:80'
    volumes:
      - wordpress-data:/bitnami/wordpress
      - apache-data:/bitnami/apache
      - php-data:/bitnami/php
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
networks:
  application_network:
    driver: overlay
    ipam:
     driver: default
     config:
       - subnet: 172.128.1.0/24

secrets:
   db_password:
     file: db_password.txt
   db_root_password:
     file: db_root_password.txt
   wp_password:
     file: wp_password.txt

volumes:
  mariadb-data:
    driver: local
  wordpress-data:
    driver: local
  apache-data:
    driver: local
  php-data:
    driver: local
